### PR TITLE
GPII-1549: Remove "dedupe" infrastructure...

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-1549](https://issues.gpii.net/browse/GPII-1549) for details.

### CODE REVIEW

**Comment by amb26** [comment]
I consistently get 2 test failures on this branch:

16:18:06.494:  jq: FAIL: Test name "Test refreshing a page..." - Message: The text field should contain the updated value... - at sequence position 6 of 11
16:18:06.495:  jq: Expected: this is new text...
16:18:06.496:  jq: Actual: this is new text...default value
16:18:06.497:  jq: Source:     at jsUnitCompat.assertEquals (E:\source\gits\gpii-test-browser\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:135:19)
    at togo (E:\source\gits\gpii-test-browser\node_modules\infusion\tests\test-core\utils\js\IoCTestUtils.js:248:33)
    at wrapped (E:\source\gits\gpii-test-browser\node_modules\infusion\tests\test-core\utils\js\IoCTestUtils.js:323:26)
    at Object.that.fire (E:\source\gits\gpii-test-browser\node_modules\infusion\src\framework\core\js\Fluid.js:1399:40)
    at Nightmare.<anonymous> (E:\source\gits\gpii-test-browser\src\js\index.js:132:36)
    at Nightmare.done (E:\source\gits\gpii-test-browser\node_modules\nightmare\lib\nightmare.js:226:15)
    at Nightmare.next (E:\source\gits\gpii-test-browser\node_modules\nightmare\lib\nightmare.js:204:28)
    at EventEmitter.<anonymous> (E:\source\gits\gpii-test-browser\node_modules\nightmare\lib\nightmare.js:214:12)
    at EventEmitter.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7) .... [output suppressed at 1024 chars - for more output, increase fluid.logObjectRenderChars]
16:18:09.711:  Nightmare browser timed out and was killed manually....
16:18:09.727:  jq: Test concluded - Test name "Test refreshing a page...": 1/2 passed - FAIL

and

16:18:33.295:  jq: FAIL: Test name "Test typing into a form field..." - Message: The text field should contain the updated value... - at sequence position 8 of
10
16:18:33.356:  jq: Expected: this is new text...
16:18:33.390:  jq: Actual: this is new text...default value
16:18:33.408:  jq: Source:     at jsUnitCompat.assertEquals (E:\source\gits\gpii-test-browser\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:135:19)
    at togo (E:\source\gits\gpii-test-browser\node_modules\infusion\tests\test-core\utils\js\IoCTestUtils.js:248:33)
    at wrapped (E:\source\gits\gpii-test-browser\node_modules\infusion\tests\test-core\utils\js\IoCTestUtils.js:323:26)
    at Object.that.fire (E:\source\gits\gpii-test-browser\node_modules\infusion\src\framework\core\js\Fluid.js:1399:40)
    at Nightmare.<anonymous> (E:\source\gits\gpii-test-browser\src\js\index.js:132:36)
    at Nightmare.done (E:\source\gits\gpii-test-browser\node_modules\nightmare\lib\nightmare.js:226:15)
    at Nightmare.next (E:\source\gits\gpii-test-browser\node_modules\nightmare\lib\nightmare.js:204:28)
    at EventEmitter.<anonymous> (E:\source\gits\gpii-test-browser\node_modules\nightmare\lib\nightmare.js:214:12)
    at EventEmitter.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7) .... [output suppressed at 1024 chars - for more output, increase fluid.logObjectRenderChars]

Also, every test fixture is preceded by deprecation messages in the console:

(electron) ipc module is deprecated. Use require("electron").ipcMain instead.
(electron) getUrl is deprecated. Use getURL instead.
(electron) loadUrl is deprecated. Use loadURL instead.

**Comment by the-t-in-rtf** [comment]
I had to make two fixes (one for the problems you encountered, one for a new bug in Nightmare 2.1.3).  These are in place now and all tests pass on Windows.

I submitted a pull request to get rid of the first two deprecation warnings in Nightmare:

https://github.com/segmentio/nightmare/pull/455

Rather than pin to my own version of nightmare indefinitely, let's see how it goes with the PR.

**Comment by the-t-in-rtf** [comment]
They merged the pull and cut a new release with two fixes we were waiting on.  I updated the PR with the new version.

**Comment by the-t-in-rtf** [comment]
As we discussed late yesterday, I added a wrapper around jQuery's `val` function as an alternative to using Nightmare's problematic `type` function.  Recent comments in [this issue](https://github.com/segmentio/nightmare/issues/414) suggest that they are working around underlying problems with Atom Electron, but have a reasonable approach in the works for the next week.

**Comment by amb26** [comment]
I got one deprecation warning when running the tests:

(electron) printToPDF is deprecated. Use webContents.printToPDF instead.

I've fixed up the problem with your Gruntfile and pushed - this is great work and should be useful across numerous projects.

**Pull request merged**
